### ISSUE TITLE
How to Flush Dispatcher Cache?

### ISSUE THREAD

**Issue by mitchross** [PRFTAdobe/aem-devkit#1]
What url/port is needed to flush the dispatcher?

![image](https://user-images.githubusercontent.com/6330506/209865772-a4187b5e-0869-413f-9932-50883c39d60d.png)

Results in connection refused

![image](https://user-images.githubusercontent.com/6330506/209865793-b2b94f70-275e-4883-8165-eba00745e2cf.png)

**Comment by mitchross** [comment]
@JHuckins

**Comment by JHuckins** [comment]
@mitchross - Thank you for the comments! I've made a number of recent commits to the project, one of which is to resolve this issue with the flush agent.

<img width="1114" alt="working-flush-request" src="https://user-images.githubusercontent.com/15619767/227053165-4b9f1386-820e-4780-b90b-7f4786c01907.png">

I advise pulling the latest changes from the main branch, and re-installing the aem-base/packages/publish-replication-agents.zip package in the publisher. That should result in a working flush agent.

**Comment by mitchross** [comment]
Thank you! I have since worked around the issue following cloud service dispatcher migration and doing alot of work on my end, but this repo was a really good starting point and hopefully someone else finds this repo as valuable as I did!
